### ISSUE TITLE
FFmpeg/HDR todo list

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3984]
Just an issue for my immediate todos, may split them into their own issues if they take longer than I think

- [ ] Fix seeking in transcoded and muxed videos in LG TVs
- [ ] Allow muxing of AAC and EAC3 tracks in tsMuxeR
- [ ] Allow tone mapping of Dolby Vision in FFmpeg (either to 8-bit or 10-bit, see what's possible)
- [ ] Allow tone mapping of Dolby Vision in MEncoder (either to 8-bit or 10-bit, see what's possible)
